Add `override_album_path_config` hook
MoeMusic/Moe pull request #281
Opened 2024-10-17 05:58 UTC by ali-ramadhan

- [x] I have read the contributing guide in the documentation.

### Description
This PR adds a new hook to the move plugin called `override_album_path_config` which allows plugins to modify the album path configuration dynamically based on the album's properties.

For more context, see: https://github.com/orgs/MoeMusic/discussions/231 

TODO:
- [ ] Add some docs in `move.rst`.

### Additional information

@jtpavlock I took a stab at implementing the `override_album_path_config` hook we discussed and added some tests which seem to pass! But I'm not totally sure that I adhered to moe's design/coding philosophy as I'm still familiarizing myself with the code base. Would appreciate any feedback!

2024-10-17 12:52 UTC, ali-ramadhan commented
Ah woops I forgot to follow the commit message guidelines. I should be able to rewrite them on this branch.

2024-10-18 01:42 UTC, jtpavlock requested changes
This looks great! I'm especially impressed with the tests, I know it probably wasn't easy trying to make sense of how I've structured my testing. I think just a few minor changes, and then clean up the commits and it should be good to go. 

For the commit, just a single feature commit would be perfect, no need to have a separate one for tests or anything.

2024-10-18 01:42 UTC, jtpavlock commented on tests/move/test_move_core.py
> +    def test_soundtrack_album(self):
Really this test (and the soundtrack logic) isn't necessary at all. You only need to test the three cases:

1. It returns a string which should override the config.
2. It returns None, and the user config should be used.
3. No plugin implementation, and the user config should be used.

1 is covered by the classical album logic, and 2 is covered by your `test_other_genre_album`, and 3 is covered by `test_no_plugin`.

2024-10-18 01:42 UTC, jtpavlock commented on tests/move/test_move_core.py
> +import datetime
I don't think any of the datetime functionality is actually necessary for any of the tests. Everything should still work if you just remove all date creations and any references to years or dates in the album paths.

2024-10-18 01:42 UTC, jtpavlock commented on moe/move/move_core.py
> +    @moe.hookspec
I think we should be able to utilize the **[first-result-only](https://pluggy.readthedocs.io/en/latest/#first-result-only)** feature of pluggy since there can only be one path template. This also means you can get rid of the "Ensure album_path_config is a string" logic since it will return the result as a string instead of a list.

2024-10-18 01:42 UTC, jtpavlock commented on moe/move/move_core.py
> +        based on the album's properties.
To me, it isn't quite clear how the new hook differentiates from `create_path_template_func` based on this description. 

Maybe "allows plugins to programmatically override the user's album path configuration"?

I also think an example would also be useful. The syntax for an example in a docstring is:

```python
        Example:
            .. code:: python

                settings.validators.register(
                    dynaconf.Validator("MOVE.ASCIIFY_PATHS", must_exist=True)
                )
```

The classical/soundtrack function you use in tests may be a perfect example.

2024-10-18 01:42 UTC, jtpavlock commented on moe/move/move_core.py
> +            If None is returned, the default configuration will be used.
I think "default configuration" may imply Moe's default configuration, which isn't the case, but rather whatever is specified in the user's configuration file will be used.

2024-10-18 01:42 UTC, jtpavlock commented on tests/move/test_move_core.py
> +        return None
Not sure if you mean to explicitly return None for clarity purposes, but it's not necessary in Python.

2025-06-04 21:13 UTC, ali-ramadhan commented on tests/move/test_move_core.py
> +    def test_soundtrack_album(self):
Agreed! I've removed `test_soundtrack_album`.

2025-06-04 21:15 UTC, ali-ramadhan commented on tests/move/test_move_core.py
> +import datetime
Agreed and done!

2025-06-04 21:18 UTC, ali-ramadhan commented on moe/move/move_core.py
> +    @moe.hookspec
Nice catch and done!

2025-06-04 21:23 UTC, ali-ramadhan commented on moe/move/move_core.py
> +        based on the album's properties.
Thanks for the syntax! I've improved the docstring and added an example.

2025-06-04 21:24 UTC, ali-ramadhan commented on tests/move/test_move_core.py
> +        return None
I do tend to `return None` for extra clarity, but I've removed it here.

2025-06-04 21:44 UTC, ali-ramadhan commented
Thanks for the thorough review @jtpavlock and apologies for dropping the ball on this PR. I believe I've addressed your code review comments so I'm requesting another review.

I know the linter is complaining about stuff in `dup_core.py` even though this PR did not touch that file (and linting passes on the master branch). Happy to fix it here though.

> For the commit, just a single feature commit would be perfect, no need to have a separate one for tests or anything.

Yeah sorry I do tend to make lots of commits then squash and merge haha. What's the best solution here? I can still squash and merge to create a `feat(move):` commit. Or I can squash the commits I have made so far.

2025-06-04 23:24 UTC, ali-ramadhan commented
Alright, managed to squash all commits into a single `feat(move)` commit.

2025-06-05 14:38 UTC, jtpavlock commented on tests/move/test_move_core.py
> +        return None
I'm not particularly opposed to it for clarity purposes, either way is good for me.

2025-06-05 14:46 UTC, jtpavlock commented
Thanks for coming back to this! I'll give it a review as soon as I can. You also should be able to rebase onto the newest main to get rid of the linting error. Every now and then a new pyright version will find some new issue with my typing.

2025-06-06 12:29 UTC, jtpavlock requested changes
This looks awesome, thanks for the changes. It's nice, it ended up being a fairly simple code change to implement. The only thing left I realized we should probably do is mention or link to the hook in the docs in the path configuration section.

2025-06-06 14:10 UTC, ali-ramadhan commented
Agreed. I just added a note in the path configuration section mentioning the new hook!

2025-06-06 15:09 UTC, merged